title: Data science portfolio - Ahmet Zamanis # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data scientist, mainly interested in time series data & models. This is a portfolio of my personal projects. 
  <br><br>
  <a href="https://www.linkedin.com/in/ahmetzamanis/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-12QW1DJCWX # your Google Analytics tracking ID here


